services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Database.db:/app/Database.db
      - ./data:/app/data
    environment:
      - TZ=Europe/Samara
    container_name: domashkatgbot
    image: domashkatgbot
    restart: no
    networks:
      - internal
    depends_on:
      - selenium
    env_file:
      - .env
  selenium:
    image: selenium/standalone-firefox
    restart: no
    networks:
      - internal
networks:
  internal:
    external: false