services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Database.db:/app/Database.db
      - ./data:/app/data
    environment:
      - TZ=Europe/Samara
    container_name: domashkatgbot
    image: domashkatgbot
    restart: no
    networks:
      - internal
    depends_on:
      - selenium
      - db
    env_file:
      - .env

  selenium:
    image: selenium/standalone-firefox
    restart: no
    networks:
      - internal

  db:
    image: postgres:latest
    restart: no
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - ./data/database:/var/lib/postgresql/data

networks:
  internal:
    external: false
